const briefRoute = require("express").Router();
const { processFiles, respond, deleteFiles, renameFile } = require('../controllers/BriefController');
const middleware = require('../middleware/userMiddleware');
const multer = require("multer");
const upload = multer({ storage: multer.memoryStorage() });
briefRoute.post("/processFiles", middleware, upload.array("files"), processFiles);
briefRoute.post("/respond", middleware, respond);
briefRoute.put('/renameFile/:fileId', middleware, renameFile);
briefRoute.delete('/deleteFile/:fileId', middleware, deleteFiles);
module.exports = briefRoute;